# -*- coding: utf-8 -*-
"""AS15955_Rigor&Reproducibility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxkUY3djj8GxSo8IgJvcXRwd1ixj_S5p
"""

## print today's date
import datetime
today = datetime.date.today()
print(today)

## Print a simple arithmatic operator like 3*8
print(2*5)

"""GitHub has multiple features that innately allows it to help with reproducibility. For eaxmple, GitHub keeps the date and version of the files with their tracking history. You can make sure that any collaborative file or submitted code is the uptodate version or get a sense of which program version is required to run it properly like it originally was. Secondly, most researchers will keep a README file and documentation with their code so that people can follow the code and methodology as closely as possible. Lastly, GitHub is designed for collaborative work by having settings that allows for respositories and the content within to be edited in a similar manner to a google document. This means that things can be regularly updated and the program will maintain version history and information."""